### ISSUE TITLE
Link to Nvidia Driver 470.05 Download for WSL 2

### ISSUE THREAD

**Issue by AlonsoCerpa** [markstrefford/running-detectron2-on-windows-wsl2-rtx30xx#3]
Hello, I only wanna comment that I found the NVIDIA driver 470.05 (compatible with WSL 2 and RTX 30XX cards) in this link:
https://www.reddit.com/r/gpumining/comments/m5so68/nvidia_driver_47005_download_link/

Maybe you could close this issue and add the link to your readme.

Regards, Alonso.

**Comment by markstrefford** [comment]
Thanks but I'd rather stick to approved links from Nvidia, etc. rather than unproven google drive links.
